# Generated by Django 2.2.6 on 2019-10-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('sex', models.CharField(choices=[('0', '女'), ('1', '男')], max_length=1, verbose_name='性别')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='电话')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='删除用户')),
                ('create_data', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
                ('updata', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user_info',
            },
        ),
    ]
